### ISSUE TITLE
SCSS token pattern

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/graphics-components#104]
### The problem

OK, so currently, we're creating CSS classes that represent style tokens, e.g., `.font-sans`, `.text-xs`, `.font-light`, etc.

This is a good for folks using those utilities directly in Svelte components to compose a set of styles together, Tailwind-style.

```svelte
<p class="font-sans text-xs font-light">Lorem ipsum</p>
```

But there are cases where we need to (or prefer to) compose those styles inside SCSS. 

I think we should extend our tokens using sass's [`@extends`](https://sass-lang.com/documentation/at-rules/extend/) rule ([instead of `@mixin`](https://sass-lang.com/documentation/at-rules/extend/#extends-or-mixins)): 

```svelte
<style lang="scss">
@use "...../font-family";

p {
  @extend .font-sans;
  @extend .text-sm;
  @extend .font-light;
}
</style>
```

Trouble is the `@use` rule required to use `@extend` pulls in a lot of _unused_ styles that Svelte will complain about endlessly. For example, with a stylesheet like:

```scss
.font-mono { /* ... */ }
.font-sans { /* ... */ }
.font-serif { /* ... */ }
```

... and an Svelte component that extends one of those rules...

```svelte
<style lang="scss">
@use "...../font-family";

p {
  @extend .font-sans;
}
</style>
```

Svelte will complain about the unused rules for `.font-mono` and `.font-serif`.

We could ignore these warnings, but that means killing a useful tool in Svelte to clean up styles and making it even harder to find legitimate errors in the callstack. **Not great.**

### Solution

`@extend` also works with [placeholder selectors](https://sass-lang.com/documentation/at-rules/extend/#placeholder-selectors). These don't create style rules themselves _unless_ they're extended. 

That means a stylesheet like:

```scss
%font-mono { /* ... */ }
%font-sans { /* ... */ }
%font-serif { /* ... */ }
```

... extended like ...

```svelte
<style lang="scss">
@use "...../font-family";

p {
  @extend %font-sans;
}
</style>
```

... won't create any unused styles and still compiles to the efficient CSS that `@extend` gives us.

The downside is we need to isolate these placeholders from their class-based counterparts, which means each token has to be defined twice: once as a placeholder and again as a class, each in a separate file.

Alternatives considered and ruled out include pairing classes with CSS variables (creates **massive** root definitions that are effectively impossible to prune) and creating mixins (not as efficient as `@extend` for the same effort).

### Proposed convention

Suggest we isolate tokens in their own directory and put placeholders next to their class definitions in a `extenders` directory...

```bash
tokens/
  text/
    extenders/
      _font-family.scss
      ...
       _main.scss #Combine all tokens
    _font-family.scss
    ...
    _main.scss #Combine all classes
```

... and to make sure we only define actual rules in a single place, make sure the class definitions use the placeholders:

```scss
// tokens/text/extenders/_font-family.scss
%font-sans {
  font-family: sans-serif;
}
```

```scss
// tokens/text/_font-family.scss
@use "extenders/font-family";

.font-sans {
  @extend %font-sans;
}
```

When combined altogether we get two separate styles we can use in both HTML and SCSS.

```svelte
<!-- Works via rolled up class definitions -->
<p class="font-sans">Lorem <span>ipsum...</span></p>

<style lang="scss">
@use "../extenders";
// Works via rolled up extenders/placeholders
span {
  @extend %font-mono;
}
</style>
```

To document all this, I'll add a third column to all our CSS doc tables for the SCSS placeholder.

Added benefit of the tokens separation, if we exclusively use "extenders"/placeholders in our components, then the Tailwind-y utility classes _can be_ opt-in. 

---

cc: @pkd2512

**Comment by hobbes7878** [comment]
... basically the convention proposed here for making utility framework: https://blog.logrocket.com/css-utility-classes-library-extendable-styles/

**Comment by hobbes7878** [comment]
See `text/` for example of how this'll look: 
https://github.com/reuters-graphics/graphics-components/tree/type-system/src/scss/text

And `Headline` component for how it'll be used in SCSS:
https://github.com/reuters-graphics/graphics-components/blob/type-system/src/components/Headline/Headline.svelte#L87

**Comment by pkd2512** [comment]
This looks good, given the alternatives have more downsides to the same usage pattern.

Thanks and regards,
__________________________________

Prasanta Kumar Dutta
Data Visualization Developer | Reuters Graphics

Thomson Reuters
the answer company

***@***.******@***.***>


From: Jon McClure ***@***.***>
Date: Tuesday, 25 July 2023 at 12:39 AM
To: reuters-graphics/graphics-components ***@***.***>
Cc: Dutta, Prasanta Kumar (Reuters) ***@***.***>, Mention ***@***.***>
Subject: [EXT] [reuters-graphics/graphics-components] SCSS token pattern (Issue #104)
External Email: Use caution with links and attachments.

The problem

OK, so currently, we're creating CSS classes that represent style tokens, e.g., .font-sans, .text-xs, .font-light, etc.

This is a good for folks using those utilities directly in Svelte components to compose a set of styles together, Tailwind-style.

<p class="font-sans text-xs font-light">Lorem ipsum</p>

But there are cases where we need to (or prefer to) compose those styles inside SCSS.

The best way to extend semantic classes like our tokens is using sass's @extends<https://urldefense.com/v3/__https:/sass-lang.com/documentation/at-rules/extend/__;!!GFN0sa3rsbfR8OLyAw!ZFYvTJRk7Y8N0phlR171EqqYh46Gphp7g0y-VfArr5CkqkAoZHIuPaIiF71dwn2XTBd5j7229VjI0CtqKBOkFQhvr2Q1HGKPWXjgvg$> rule (instead of @mixin<https://urldefense.com/v3/__https:/sass-lang.com/documentation/at-rules/extend/*extends-or-mixins__;Iw!!GFN0sa3rsbfR8OLyAw!ZFYvTJRk7Y8N0phlR171EqqYh46Gphp7g0y-VfArr5CkqkAoZHIuPaIiF71dwn2XTBd5j7229VjI0CtqKBOkFQhvr2Q1HGIaOwlsXA$>):

<style lang="scss">

@use "...../font-family";



p {

  @extend .font-sans;

  @extend .text-sm;

  @extend .font-light;

}

</style>

Trouble is the @use rule required to use @extend pulls in a lot of unused styles that Svelte will complain about endlessly. For example, with a stylesheet like:

.font-mono { /* ... */ }

.font-sans { /* ... */ }

.font-serif { /* ... */ }

... and an Svelte component that extends one of those rules...

<style lang="scss">

@use "...../font-family";



p {

  @extend .font-sans;

}

</style>

Svelte will complain about the unused rules for .font-mono and .font-serif.

We could ignore these warnings, but that means killing a useful tool in Svelte to clean up styles and making it even harder to find legitimate errors in the callstack. Not great.

Solution

@extend also works with placeholder selectors<https://urldefense.com/v3/__https:/sass-lang.com/documentation/at-rules/extend/*placeholder-selectors__;Iw!!GFN0sa3rsbfR8OLyAw!ZFYvTJRk7Y8N0phlR171EqqYh46Gphp7g0y-VfArr5CkqkAoZHIuPaIiF71dwn2XTBd5j7229VjI0CtqKBOkFQhvr2Q1HGIfG5IpRg$>. These don't create style rules themselves unless they're extended.

That means a stylesheet like:

%font-mono { /* ... */ }

%font-sans { /* ... */ }

%font-serif { /* ... */ }

... extended like ...

<style lang="scss">

@use "...../font-family";



p {

  @extend %font-sans;

}

</style>

... won't create any unused styles and still compiles to the efficient CSS that @extend gives us.

The downside is we need to isolate these placeholders from their class-based counterparts, which means each token has to be defined twice: once as a placeholder and again as a class, each in a separate file.

Alternatives considered and ruled out include pairing classes with CSS variables (creates massive root definitions that are effectively impossible to prune) and creating mixins (not as efficient as @extend for the same effort).

Proposed convention

Suggest we isolate placeholders next to their class definitions in a -tokens suffixed partial...

text/

  _font-family.scss

  _font-family-tokens.scss

  ...

  _main.scss #Combine all classes

  _tokens.scss #Combine all tokens

... and to make sure we only define actual rules in a single place, make sure the class definitions use the placeholders:

// _font-family-tokens.scss

%font-sans {

  font-family: sans-serif;

}

// _font-family.scss

@use "font-family-tokens";



.font-sans {

  @extend %font-sans;

}

When combined altogether we get two separate styles we can use in both HTML and SCSS.



<p class="font-sans">Lorem <span>ipsum...</span></p>



<style lang="scss">

@use "../tokens";

// Works via rolled up tokens/placeholders

span {

  @extend %font-mono;

}

</style>

To document all this, I'll add a third column to all our CSS doc tables for the SCSS placeholder.

________________________________

cc: @pkd2512<https://urldefense.com/v3/__https:/github.com/pkd2512__;!!GFN0sa3rsbfR8OLyAw!ZFYvTJRk7Y8N0phlR171EqqYh46Gphp7g0y-VfArr5CkqkAoZHIuPaIiF71dwn2XTBd5j7229VjI0CtqKBOkFQhvr2Q1HGLd3pValg$>

**Comment by hobbes7878** [comment]
Closing this because my conclusions were all wrong and I must out with the evidence of my shame...
