### ISSUE TITLE
Scroller component alt text fixes

### ISSUE THREAD

**Issue by MinamiFunakoshiTR** [reuters-graphics/graphics-components#13]
For discussion about improving the Scroller component to make it work better for screen readers. Please leave comments if you have suggestions or thoughts. Thanks!

## Problem
The html text in the background graphic (which is often ai2svelte) is usually unintelligible and unhelpful for screen readers.

## Suggested fixes from the a11y workforce 
In `Scroller/Background.svelte`:
- Add an option to add `ariaDescription` and `visually-hidden` class to each `<div class="step-background">`, following the same pattern we use in the [Ai2svelte component](https://github.com/reuters-graphics/graphics-svelte-components/blob/master/src/lib/Ai2svelte/index.svelte#L21-L43)
- Make it so you can write `ariaDescription` for a background graphic in the google doc

## For discussion
I propose hiding all background graphics from screen readers by default by adding `aria-hidden="true"` since, in most cases, the foreground text might be enough to explain the background graphic. If there are many steps, it could also be a lot of work to add aria description for each background graphic.

What do you think?

## Next steps
Once we agree on the fixes, I'll make a branch, make the fixes, and make a PR.

## References for best practices
Read about `aria-hidden` [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden):

> Adding aria-hidden="true" to an element removes that element and all of its children from the accessibility tree. This can improve the experience for assistive technology users by hiding purely decorative content, such as icons or images, etc...
       
Semantic html is recommended as part of [best practices](http://web-accessibility.carnegiemuseums.org/foundations/semantic/#:~:text=Structural%2C%20semantic%20HTML%20is%20the,read%20by%20a%20screen%20reader.).

**Comment by hobbes7878** [comment]
Revisiting to say I think this will need a new PR post the great Storybook migration of the summer.

I understand and agree with making the background component aria-hidden by default, but configurable.

Re: supplying the aria text to describe background, I _think_ what you want here is an aria prop on the foreground steps. For two reasons: 1) Svelte doesn't actually alternate the markup for the background component with the foreground ones. Instead, I think what you'd end up with is all the background arias are read together first, and then all the foreground ones. Or worse, the background is added _after_ the screen reader has moved to the foreground, so it'll miss it. 2) I think having extra aria on the foreground makes it easy to handle both situations you described: If you want to describe the background in detail first, then your first foreground step has that description. If you want to describe each background in sequence, then you'd add that to each foreground aria.

I agree the presence or absence of foreground aria shouldn't be an error here. I'm inclined not to warn about it either because I do see cases where the text does a good job describing the image and with the different configurations possible using foreground aria, it might trigger confusing false positives. Better handled by our graphics editors _to edit_, basically...

**Comment by MinamiFunakoshiTR** [comment]
Looping back to this. @hobbes7878 that all sounds good to me. So, the suggested changes are:

- Add an extra aria option on each foreground step to describe the background. This would be optional for each step, which means we have the option to add just one aria text for all backgrounds in the scroll section if we don't want to add aria text for each background.
- Make all backgrounds aria-hidden true, always (not configurable)
- Add a field for background alt text in the google doc 

How does this sound to everyone? @hobbes7878  @juruwolfe  @AditiBhandariTR @pkd2512  @Daisy-Chung-TR

**Comment by MinamiFunakoshiTR** [comment]
Looping back to this -- will make a new PR in the storybook repo with the changes above.

**Comment by MinamiFunakoshiTR** [comment]
Done via https://github.com/reuters-graphics/graphics-components/pull/50
