### ISSUE TITLE
Scroller snap functionality

### ISSUE THREAD

**Issue by travishartman** [reuters-graphics/graphics-components#33]
So it seems snap is a prop in the graphicBlock, but not surfaced as a prop in the Scroller. it seems to default to fluid resize.  How to apply snapping to the scroller? 
Is this documented somewhere?  I have not been able to find either a) explicit info on how to set prop for snap in scroller or b) how ai-graphicBlock is pulled in upstream from scroller and how to apply on that facet.  Happy to explain in more detail if needed.

**Comment by hobbes7878** [comment]
For ai2svelte, the "snapping" is handled in Illustrator directly. There's a `responsiveness` ai2html setting you can set to `fixed` in your Illustrator file to do the trick.

**Comment by travishartman** [comment]
yeah figured that was being overridden somewhere as that is already set to "fixed" in AI as the default and yet the scroller ai2html is not respecting the "fixed" setting, as it is still scaling fluidly.

**Comment by hobbes7878** [comment]
Nah, something else must be going on. The Scroller doesn't have access to those settings. Starting to sound like something in ai2svelte.

Trav, can you set up a minimal example repo? I'm in Scotland through the weekend, but maybe @fcage could take a quick look to at least help diagnose your ick. Otherwise, I'll take a look when back.

**Comment by travishartman** [comment]
think i've resolved this, it may have been some errant css i added in that i've made more specific.  my bad.

**Comment by hobbes7878** [comment]
Glad it fixed itself.
