### ISSUE TITLE
GraphicBlock no longer has Source attribute

### ISSUE THREAD

**Issue by AditiBhandariTR** [reuters-graphics/graphics-components#44]
The GraphicBlock only has a notes attribute and not a source attribute. Since the source and notes can be handled in the same attribute on the Google Doc, I suggest we remove it from the gdoc template

**Comment by hobbes7878** [comment]
So in the archieml template, we have`\Source:`, and that `\` is actually an escape so ArchiML _doesn't_ treat it as a key, which is why it's in black not blue.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/2772078/206264796-5ebc6a8b-019a-4250-afdd-c9a75989fe83.png">

The key is actually `Notes:`, which lines up with the component and with the docs for the component which have the same (unfortunately w/out more useful ArchieML colourings, tho...)

<img width="873" alt="image" src="https://user-images.githubusercontent.com/2772078/206265152-a59335c8-c431-487a-90f2-47a212e61acf.png">

Gonna close this out, but if you're seeing something else I'm not, feel free to re-open.

**Comment by hobbes7878** [comment]
Noting Aditi pointed out a stray `Source:` separate from `Notes:` in the archieml kit template. Deleted.
