### ISSUE TITLE
Make location of <Theme> component more prominent in docs

### ISSUE THREAD

**Issue by allyjlevine** [reuters-graphics/graphics-components#47]
A few of us on the AMERS desk have run into this same issue. Could we specify more prominently that the `Theme` component is located in `+page.svelte`? It's currently in the docs as a grayed out note, but it'd be helpful to repeat the location down the docs page in relevant sections. For example, I would have found it helpful in the "Custom theme" section because those are the instructions I was following to make my own custom page background. I was making the mistake of adding the `Theme` component to `App.svelte` and wrapping it around the `Article` tag.

Attached is a screenshot of where it would have been helpful for me
<img width="1105" alt="Screen Shot 2023-01-17 at 2 39 54 PM" src="https://user-images.githubusercontent.com/10169796/212996539-0789f0f1-819d-4d70-869b-975c9309f92b.png">

Tagging @MinamiFunakoshiTR for visibility

**Comment by MinamiFunakoshiTR** [comment]
FYI @hobbes7878, I couldn't override the background-color on `body` in `global.scss`. The `<Theme>` component in `+page.svelte` seems to override it, even when I add `!important` to the css.

**Comment by hobbes7878** [comment]
I see two separate things here:

On the note: Can't make it more prominent than a callout at the top of the component's page, I think, which follows the placement for other important notes on components. Gotta _read_ the docs, though, and not just skip to the copy-paste to get it, but I'm calling that a feature not a flaw.

On background CSS: Yes, theme colour is designed to be updated through the `Theme` component, rather than SCSS, which applies it to many other places where background colour is used. The note to add an additional line of CSS is specifically for when you scroll off the top of the page and you get that momentary margin of white at the top. Not strictly necessary, but if it bugs you, that little CSS takes care of it.
