### ISSUE TITLE
A11y review: Table

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/graphics-components#64]
Hey @juruwolfe, Welsh added a new component would be good to get the a11y team to audit at their leisure:
https://reuters-graphics.github.io/graphics-components/?path=/docs/components-table--default

Anyone in that group I can pin this ticket to?

**Comment by juruwolfe** [comment]
Oh yeah I can take a look once I'm back

**Comment by hobbes7878** [comment]
All yours. Thanks mucho.

**Comment by palewire** [comment]
Very nice. If I can help, let me know. 

Two things on my mind:
- Since we broke the metadata out of the `<caption`> tag, should we consider a ` aria-describedby` that links the table to the header, as described in "Approach #2" [here](https://www.w3.org/WAI/tutorials/tables/caption-summary/).
- Should we scope the rows by default by making the first cell a `<th>`, as shown [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#scoping_rows_and_columns)? I've never known if that's something that ought to be universal, or only when the first cell signifies something unique about the record.
